// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA65tdRm7PJa95mZd7NP4G1jgqQsCnTgYU',
    appId: '1:918381685194:web:0035e9f99531ea2fb94733',
    messagingSenderId: '918381685194',
    projectId: 'cardiaccare-logging',
    authDomain: 'cardiaccare-logging.firebaseapp.com',
    storageBucket: 'cardiaccare-logging.firebasestorage.app',
    measurementId: 'G-7SJGWRK1Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkkK_9QQpQ5uuDa1QpmulAsgJUit3pBQ',
    appId: '1:918381685194:android:c24b91943d98c196b94733',
    messagingSenderId: '918381685194',
    projectId: 'cardiaccare-logging',
    storageBucket: 'cardiaccare-logging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgn12Rn0kV3X9q6I0zXnWmk5F9oOWmQMw',
    appId: '1:918381685194:ios:b2fbc0c5bad3ae4bb94733',
    messagingSenderId: '918381685194',
    projectId: 'cardiaccare-logging',
    storageBucket: 'cardiaccare-logging.firebasestorage.app',
    iosBundleId: 'com.example.cardioCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgn12Rn0kV3X9q6I0zXnWmk5F9oOWmQMw',
    appId: '1:918381685194:ios:b2fbc0c5bad3ae4bb94733',
    messagingSenderId: '918381685194',
    projectId: 'cardiaccare-logging',
    storageBucket: 'cardiaccare-logging.firebasestorage.app',
    iosBundleId: 'com.example.cardioCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA65tdRm7PJa95mZd7NP4G1jgqQsCnTgYU',
    appId: '1:918381685194:web:47eafc3c0854404db94733',
    messagingSenderId: '918381685194',
    projectId: 'cardiaccare-logging',
    authDomain: 'cardiaccare-logging.firebaseapp.com',
    storageBucket: 'cardiaccare-logging.firebasestorage.app',
    measurementId: 'G-FKDRP7Z2K2',
  );
}
